### ISSUE TITLE
Parameter Authentication failed.

### ISSUE THREAD

**Issue by mchkhawarshahzad** [maan56/EasyPaisa-Integration-PHP-Laravel#1]
Dear,
i am facing an issue related to Parameter Authentication failed.

**Comment by maan56** [comment]
Dear, This repo was just a test for a project a long time ago. I don't know what you are trying to make. EasyPaisa changes its API time-to-time, therefore this method may not work in these days.
You may contact me on Twitter if you want my service for this problem instantly. Or if you can wait some time, I'm planning to make an open-source package for this purpose very soon.

Thanks
